### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by empiricist** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#110]
Whenever I try to launch the game, it crashes with a [NullPointerException](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1423808/fml-client-latest.log).  I am using:
Minecraft 1.11.2
Forge 13.20.1.2386
Valkyrian Warfare 0.9 (from curseforge) or build 107 (from the jenkins)

I have previously used 0.9_pre_2 with no problems.

**Comment by Best108** [comment]
Should be fixed soon with the addon file added, I'll update the download once we push out the latest version.

**Comment by AireagoirSteam** [comment]
Is build 108 fixed since I get it to when using multimc?

**Comment by empiricist** [comment]
It still crashes with what appears to be the same error.

[fml-client-latest.log](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/1455528/fml-client-latest.log)

**Comment by CTH999** [comment]
I have the same thing happen to me, but it seems that not every on has it. Strange.

**Comment by DaMatrix** [comment]
This should be fixed with the final 1.11.2 release.
