### ISSUE TITLE
Ship Physics randomly stop entirely.

### ISSUE THREAD

**Issue by Meowlala** [ValkyrienWarfare/Valkyrien-Warfare-Revamped#64]
I'm running version 87 off of curseforge and the ships stop moving altogether at seemingly random moments. After this, I'm unable to interact with anything on the ship. (break blocks, change controls, etc.) It seems to be some form of desync, as logging off and back on reloads the ship in a completely different place, functional for the next minute or so.

**Comment by DaMatrix** [comment]
Can we see your log, do you have any other mods installed (if so, which ones), what are your PC specs?

**Comment by BigBastard** [comment]
I believe this issue has to do with how Ships try to interpolate their positions in the case of server lag. Your client probably went 20+ ticks without getting an update from the server, causing the permanent desync.

I'm looking into it, and hoping to have it fixed soon.

**Comment by Liiw** [comment]
Hello!

I had a similar issue on our Spongeforge server. I added this mod (build 96) to the numerous other mods already installed on the server and tried to build a test barge. I experienced similar issues I posted in #66. Upon infusing the craft with physics, it started jumping like a wild horse, After it had settled down in a canyon, it sat there, crooked. I could not access the hovercraft controller or break any of the blocks of the ship. I am also attaching a fml-server-latest log I pulled from the server after I shut it down.

[fml-server-latest.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/829000/fml-server-latest.txt)

I took a glimpse at this and saw that some mods seem to have an issue with VW (Gendustry and Opencomputers). I have very little knowledge of JAVA or the forge/spongeforge API however, so for all I know, this could be normal.

**Comment by BigBastard** [comment]
Strange, I know that Sponge works on its own with VW. The mod also works perfectly fine with the DireWolf20 pack from what I can tell. 

As for Gendustry and Open Computers, I think I know the cause from the logs. I'll investigate why they're causing ASM failures and how I can fix these.

**Comment by Liiw** [comment]
That would probably indicate that this could be a mod conflict, because I do not have any standard packs installed. Is there a quicker alternative to tracing that than adding mods one-by one?

**Comment by BigBastard** [comment]
Not particularly, from the log I saw the ships didn't put out a freezing message. I've fixed the incompatibility With Open Computers in the latest build, but I don't think that affects this problem as a whole. I'll look into it further once I get home.

**Comment by Liiw** [comment]
I was curious if maybe the last build (98) didn't have this freezing issue, unfortunately it still persists. I'm uploading an image just so you could visualize it better. The bigger "ships" lunged into air after infusing, bounced and flipped after landing, then froze. 

![image](https://cloud.githubusercontent.com/assets/14122419/23777508/f6aab992-053d-11e7-8b30-3fbaeb0f5057.png)

The smaller one in the background casually slid into the sea. It was lagging with the physics a bit, but didn't freeze. I was confused as to why it didn't rise to Y 76 as I instructed the controller, but then I realized I forgot to link the ether compressor and the hovercraft controller. After linking the two, it flew to the assigned Y level where it stay swiveling. It froze after I attached the second ether compressor:

![image](https://cloud.githubusercontent.com/assets/14122419/23777648/cc4413be-053e-11e7-8866-0b14fd88fb62.png)

I wandered away from the spawnpoint, built some vessels without the ether compressors and only regular thruster engines installed. These vessels seem to take longer to freeze. I came back to the spawnpoint to see this:

![image](https://cloud.githubusercontent.com/assets/14122419/23777911/39af9760-0540-11e7-8d40-6e2df3698e89.png)

The ships responded to changing the Y level, but froze after a while. This all happened in a fresh SP world. I'm uploading the fml-client-latest just in case it could prove helpful:

[fml-client-latest.txt](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/832740/fml-client-latest.txt)

**Comment by BigBastard** [comment]
Can you send me your mods .zip? From your description I think it has something to do with the way Ships determine when to unload themselves, and if thats the case I might be able to fix this with a few lines of code!

**Comment by Liiw** [comment]
I cannot upload the .rar here, because it's too big. I am posting it on Dropbox and sharing the link here:

https://www.dropbox.com/home/Mods%20folder%20of%20Liiw

Running on:
MC 1.10.2
forge  1.10.2-12.18.3.2239   

Thank you for your continued effort in fixing this issue!

**Comment by BigBastard** [comment]
That's the link to your dropbox -_- . Nobody can access that but you.

**Comment by Liiw** [comment]
Damn, How could I have missed that. I'm so sorry! Here is the sharelink:

https://www.dropbox.com/sh/0t2kqyixs3r5lz0/AAACV7nEPX-6ZCrQb9jeRiX5a?dl=0

**Comment by BigBastard** [comment]
The conflict was caused by ChickenChunks using some terrible code to accomplish its chunk unloading.

Thankfully because the lazy ChunkLoading relied on an event, I managed to write a method that hides all the Ship Chunks from ChickenChunks before it starts its purge, allowing me to bypass what should be an unloading.

Build #99 should be the death of this bug https://jenkins.ironhide.de/job/Valkyrien-Warfare-Revamped/99/ .

I just want to say thanks to @Liiw for all the support in getting me concrete scenarios that made debugging this possible in the first place (<3); and as usual, if I'm wrong and this bug persists please be sure to let me know on this thread. <3

**Comment by Liiw** [comment]
The beast has been slain! No more freezing ships! I did have the occasional stutter, but that was probably due to the SP world generating while I was sailing the majestic hoverbarges:

However I do have other issues, which I will be addressing in a separate thread (ships behaving strangely).
